//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export interface Portfolio
{
	id: number;
	displayName: string|null;
	files: PortfolioFile[];
}
export interface PortfolioFile
{
	id: string;
	name: string|null;
	path: string|null;
}
export interface UpdatePortfolio
{
	displayName: string|null;
	id: number;
	files: any[];
}
export interface CreatePortfolio
{
	displayName: string|null;
	files: any[];
}
export interface DeletePortfolio
{
	id: number;
}
export interface Unit
{
}
export interface IConfigurationMeta
{
	route: string|null;
	title: string|null;
	id: string|null;
	sectionId: string|null;
}
export interface EntityChanged
{
	key: { [key:string]: any };
	state: number;
	entityName: string|null;
}
