// this file is autogenerated. To not edit.

export interface Foo {
  property0: string
  property1: number
  property2: number | null
  property3: string
  property4: string | null
  property5: string | null
  property6: string
  property8: Bar
  property9: any[]
  property10: number[]
  property11: string[]
  property12: Bar[]
  property13: Bar[]
  myProperty14: { [key: string]: string }
  myProperty15: { [key: string]: any }
  myProperty16: string[]
  myProperty17: string[]
}

export const defaultFoo: Foo = {
  property0: "",
  property1: 0,
  property2: null,
  property3: "00000000-0000-0000-0000-000000000000",
  property4: null,
  property5: null,
  property6: "1/1/0001 12:00:00 AM",
  property8: null as any,
  property9: [],
  property10: [],
  property11: [],
  property12: [],
  property13: [],
  myProperty14: {},
  myProperty15: {},
  myProperty16: [],
  myProperty17: [],
}

export interface Bar {
  property0: number
}

export const defaultBar: Bar = {
  property0: 0,
}

export interface PutPortfolioFile {
  id: string
  name: string
}

export const defaultPutPortfolioFile: PutPortfolioFile = {
  id: "00000000-0000-0000-0000-000000000000",
  name: "",
}

export interface CreatePortfolio {
  displayName: string
  files: PutPortfolioFile[]
}

export const defaultCreatePortfolio: CreatePortfolio = {
  displayName: "",
  files: [],
}

export interface UpdatePortfolio {
  displayName: string
  id: number
  files: PutPortfolioFile[]
}

export const defaultUpdatePortfolio: UpdatePortfolio = {
  displayName: "",
  id: 0,
  files: [],
}

export interface Portfolio {
  id: number
  displayName: string
  files: PortfolioFile[]
}

export const defaultPortfolio: Portfolio = {
  id: 0,
  displayName: "",
  files: [],
}

export interface PortfolioFile {
  id: string
  name: string
  path: string
}

export const defaultPortfolioFile: PortfolioFile = {
  id: "00000000-0000-0000-0000-000000000000",
  name: "",
  path: "",
}

export module Entities {
  export type Foo = "Glow.Sample.Test+Foo"
  export type Bar = "Glow.Sample.Test+Bar"
  export type PutPortfolioFile = "Glow.Sample.Files.PutPortfolioFile"
  export type CreatePortfolio = "Glow.Sample.Files.CreatePortfolio"
  export type UpdatePortfolio = "Glow.Sample.Files.UpdatePortfolio"
  export type Portfolio = "Glow.Sample.Files.Portfolio"
  export type PortfolioFile = "Glow.Sample.Files.PortfolioFile"

  export type All = Foo | Bar | PutPortfolioFile | CreatePortfolio | UpdatePortfolio | Portfolio | PortfolioFile
}
